name: VCMI

on:
  push:
    branches:
      - tmp-feature-test
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  deploy-src:
    # if: always() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Build Number
          run: |
            source '${{github.workspace}}/CI/get_package_name.sh'
            echo VCMI_PACKAGE_FILE_NAME="$VCMI_PACKAGE_FILE_NAME" >> $GITHUB_ENV
          env:
            PULL_REQUEST: ${{ github.event.pull_request.number }}

        - name: Create source code archive (including submodules)
          run: |
            git archive HEAD -o "release.tar" --worktree-attributes -v
            git submodule update --init --recursive
            git submodule --quiet foreach 'cd "$toplevel"; tar -rvf "release.tar" "$sm_path"'
            gzip release.tar
            
        - name: Upload source code archive
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.VCMI_PACKAGE_FILE_NAME }}
            path: |
              ./release.tar.gz
